# Generated by Django 5.0 on 2026-03-05 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_item_amountpurchased'),
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.location'),
        ),
    ]
